language: java

jdk:
- oraclejdk8

before_script:
  - pip install --user codecov

script: "./gradlew distZip"

after_success:
- codecov

addons:
        artifacts:
                paths:
                        - "$( ls -1 ./ui/build/distributions/*.zip )"

