language: java

script: gradle distZip

after_script:
        - test -f ./build/distributions/*.zip

addons:
        artifacts: true
        s3_region: "europe-1"
        artifacts:
                paths:
                        - $( ls -1 ui/build/distributions/*.zip )

