package com.google.code.reelcash.dialogs;

import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author andrei.olar
 */
public abstract class JRegistryDialog extends javax.swing.JDialog implements TableModelListener {

    private static final long serialVersionUID = -1232185025978975113L;

    /** Creates new form JRegistryDialog */
    public JRegistryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        postInitComponents();
    }

    protected void postInitComponents() {
        getTableModel().addTableModelListener(this);
    }

    /**
     * Implement this method in order to provide the means for data population.
     *
     * @return an {@link javax.swing.table.AbstractTableModel} instance.
     */
    public abstract AbstractTableModel getTableModel();

    /**
     * Override this to provide handling for the case when the table model has
     * changed.
     *
     * @param e parameter which describes the changes.
     */
    public void tableChanged(TableModelEvent e) {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    dataBar = new javax.swing.JToolBar();
    addItemButton = new javax.swing.JButton();
    editItemButton = new javax.swing.JButton();
    deleteItemButton = new javax.swing.JButton();
    contentPane = new javax.swing.JPanel();
    dataScroller = new javax.swing.JScrollPane();
    dataTable = new javax.swing.JTable();
    editPanel = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    dataBar.setRollover(true);

    addItemButton.setMnemonic('n');
    addItemButton.setText("New");
    addItemButton.setToolTipText("Add a new item");
    addItemButton.setFocusable(false);
    addItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    dataBar.add(addItemButton);

    editItemButton.setMnemonic('e');
    editItemButton.setToolTipText("Edit the selected item");
    editItemButton.setFocusable(false);
    editItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    editItemButton.setLabel("Edit");
    editItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    dataBar.add(editItemButton);

    deleteItemButton.setMnemonic('d');
    deleteItemButton.setText("Delete");
    deleteItemButton.setToolTipText("Delete the selected item");
    deleteItemButton.setFocusable(false);
    deleteItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    deleteItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    dataBar.add(deleteItemButton);

    getContentPane().add(dataBar, java.awt.BorderLayout.PAGE_START);

    contentPane.setLayout(new java.awt.CardLayout());

    dataTable.setModel(getTableModel());
    dataScroller.setViewportView(dataTable);

    contentPane.add(dataScroller, "table");

    editPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 15));
    contentPane.add(editPanel, "edit");

    getContentPane().add(contentPane, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addItemButton;
  private javax.swing.JPanel contentPane;
  private javax.swing.JToolBar dataBar;
  private javax.swing.JScrollPane dataScroller;
  private javax.swing.JTable dataTable;
  private javax.swing.JButton deleteItemButton;
  private javax.swing.JButton editItemButton;
  private javax.swing.JPanel editPanel;
  // End of variables declaration//GEN-END:variables
}
