/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UserSettingsJDialog.java
 *
 * Created on Jan 15, 2010, 5:05:33 PM
 */

package com.google.code.reelcash.dialogs;

/**
 *
 * @author andrei.olar
 */
public class UserSettingsJDialog extends javax.swing.JDialog {

    /** Creates new form UserSettingsJDialog */
    public UserSettingsJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    companyNameLabel = new javax.swing.JLabel();
    companyNameField = new javax.swing.JTextField();
    cifLabel = new javax.swing.JLabel();
    cifField = new javax.swing.JTextField();
    orcLabel = new javax.swing.JLabel();
    orcField = new javax.swing.JTextField();
    hqAddressLabel = new javax.swing.JLabel();
    hqAddressField = new javax.swing.JTextField();
    admRegionLabel = new javax.swing.JLabel();
    admRegionField = new javax.swing.JTextField();
    countryLabel = new javax.swing.JLabel();
    countryField = new javax.swing.JTextField();
    bankAccountLabel = new javax.swing.JLabel();
    bankAccountField = new javax.swing.JTextField();
    bankLabel = new javax.swing.JLabel();
    bankField = new javax.swing.JTextField();
    capitalLabel = new javax.swing.JLabel();
    capitalField = new javax.swing.JTextField();
    defRepNameLabel = new javax.swing.JLabel();
    defRepNameField = new javax.swing.JTextField();
    defRepIdTypeLabel = new javax.swing.JLabel();
    defRepIdTypeField = new javax.swing.JTextField();
    defRepIdLabel = new javax.swing.JLabel();
    defRepIdField = new javax.swing.JTextField();
    defRepAddrLabel = new javax.swing.JLabel();
    defRepAddrField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    getContentPane().setLayout(new java.awt.GridBagLayout());

    companyNameLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    getContentPane().add(companyNameLabel, gridBagConstraints);

    companyNameField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    getContentPane().add(companyNameField, gridBagConstraints);

    cifLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    getContentPane().add(cifLabel, gridBagConstraints);

    cifField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    getContentPane().add(cifField, gridBagConstraints);

    orcLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    getContentPane().add(orcLabel, gridBagConstraints);

    orcField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 0;
    getContentPane().add(orcField, gridBagConstraints);

    hqAddressLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    getContentPane().add(hqAddressLabel, gridBagConstraints);

    hqAddressField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 5;
    getContentPane().add(hqAddressField, gridBagConstraints);

    admRegionLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    getContentPane().add(admRegionLabel, gridBagConstraints);

    admRegionField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    getContentPane().add(admRegionField, gridBagConstraints);

    countryLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    getContentPane().add(countryLabel, gridBagConstraints);

    countryField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    getContentPane().add(countryField, gridBagConstraints);

    bankAccountLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    getContentPane().add(bankAccountLabel, gridBagConstraints);

    bankAccountField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 5;
    getContentPane().add(bankAccountField, gridBagConstraints);

    bankLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    getContentPane().add(bankLabel, gridBagConstraints);

    bankField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    getContentPane().add(bankField, gridBagConstraints);

    capitalLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    getContentPane().add(capitalLabel, gridBagConstraints);

    capitalField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 2;
    getContentPane().add(capitalField, gridBagConstraints);

    defRepNameLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    getContentPane().add(defRepNameLabel, gridBagConstraints);

    defRepNameField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    getContentPane().add(defRepNameField, gridBagConstraints);

    defRepIdTypeLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    getContentPane().add(defRepIdTypeLabel, gridBagConstraints);

    defRepIdTypeField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 5;
    getContentPane().add(defRepIdTypeField, gridBagConstraints);

    defRepIdLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 5;
    getContentPane().add(defRepIdLabel, gridBagConstraints);

    defRepIdField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 5;
    gridBagConstraints.gridy = 5;
    getContentPane().add(defRepIdField, gridBagConstraints);

    defRepAddrLabel.setText("jLabel1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    getContentPane().add(defRepAddrLabel, gridBagConstraints);

    defRepAddrField.setText("jTextField1");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.gridwidth = 5;
    getContentPane().add(defRepAddrField, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserSettingsJDialog dialog = new UserSettingsJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField admRegionField;
  private javax.swing.JLabel admRegionLabel;
  private javax.swing.JTextField bankAccountField;
  private javax.swing.JLabel bankAccountLabel;
  private javax.swing.JTextField bankField;
  private javax.swing.JLabel bankLabel;
  private javax.swing.JTextField capitalField;
  private javax.swing.JLabel capitalLabel;
  private javax.swing.JTextField cifField;
  private javax.swing.JLabel cifLabel;
  private javax.swing.JTextField companyNameField;
  private javax.swing.JLabel companyNameLabel;
  private javax.swing.JTextField countryField;
  private javax.swing.JLabel countryLabel;
  private javax.swing.JTextField defRepAddrField;
  private javax.swing.JLabel defRepAddrLabel;
  private javax.swing.JTextField defRepIdField;
  private javax.swing.JLabel defRepIdLabel;
  private javax.swing.JTextField defRepIdTypeField;
  private javax.swing.JLabel defRepIdTypeLabel;
  private javax.swing.JTextField defRepNameField;
  private javax.swing.JLabel defRepNameLabel;
  private javax.swing.JTextField hqAddressField;
  private javax.swing.JLabel hqAddressLabel;
  private javax.swing.JTextField orcField;
  private javax.swing.JLabel orcLabel;
  // End of variables declaration//GEN-END:variables

}
