package ro.samlex.reelcash.ui.components;

import javax.swing.table.TableModel;
import ro.samlex.reelcash.Application;
import ro.samlex.reelcash.data.Invoice;
import ro.samlex.reelcash.data.InvoiceItem;

public class JInvoicePanel extends javax.swing.JPanel {
    public JInvoicePanel() {
        initComponents();
    }
    
    public Invoice createInvoice() {
        final Invoice result = new Invoice();
        result.setNumber((Integer)numberSpinner.getModel().getValue());
        result.setDate((java.util.Date)dateSpinner.getModel().getValue());
        result.setEmitter(Application.getInstance().getCompany());
        result.setRecipient(invoicedContactPanel.createParty());
        TableModel model = invoiceDetailsTable.getModel();
        for(int i=0;i<model.getRowCount();i++) {
            result.getInvoicedItems().add(createInvoiceItem(model, i));
        }
        return result;
    }
    
    private InvoiceItem createInvoiceItem(TableModel model, int index) {
        final InvoiceItem item = new InvoiceItem();
        item.setName((String)model.getValueAt(index, 0));
        item.setQuantity((Integer)model.getValueAt(index, 1));
        item.setUnitPrice((Double)model.getValueAt(index, 2));
        item.setVat((Double)model.getValueAt(index, 3));
        return item;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        lblNumber = new javax.swing.JLabel();
        numberSpinner = new javax.swing.JSpinner();
        lblDate = new javax.swing.JLabel();
        dateSpinner = new javax.swing.JSpinner();
        invoicedContactPanel = new ro.samlex.reelcash.ui.components.JContactPanel();
        invoicedItemsPanel = new javax.swing.JPanel();
        invoicedItemsTableScroller = new javax.swing.JScrollPane();
        invoiceDetailsTable = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        headerPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(32, 16, 32, 16));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 4, 4);
        flowLayout1.setAlignOnBaseline(true);
        headerPanel.setLayout(flowLayout1);

        lblNumber.setText("Invoice Number:");
        headerPanel.add(lblNumber);

        numberSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        numberSpinner.setMaximumSize(new java.awt.Dimension(120, 23));
        numberSpinner.setMinimumSize(new java.awt.Dimension(45, 23));
        numberSpinner.setPreferredSize(new java.awt.Dimension(60, 23));
        headerPanel.add(numberSpinner);

        lblDate.setText("/");
        headerPanel.add(lblDate);

        dateSpinner.setModel(new javax.swing.SpinnerDateModel());
        dateSpinner.setMaximumSize(new java.awt.Dimension(240, 23));
        dateSpinner.setMinimumSize(new java.awt.Dimension(120, 23));
        dateSpinner.setPreferredSize(new java.awt.Dimension(150, 23));
        headerPanel.add(dateSpinner);

        add(headerPanel);

        invoicedContactPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(16, 8, 8, 8), "Invoiced Party Contact Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        add(invoicedContactPanel);

        invoicedItemsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(16, 8, 8, 8), "Invoiced items", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        invoicedItemsPanel.setLayout(new javax.swing.BoxLayout(invoicedItemsPanel, javax.swing.BoxLayout.Y_AXIS));

        invoiceDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"",  new Integer(1), null,  new Double(0.24)}
            },
            new String [] {
                "Name", "Quantity", "Unit Price", "VAT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        invoicedItemsTableScroller.setViewportView(invoiceDetailsTable);

        invoicedItemsPanel.add(invoicedItemsTableScroller);

        add(invoicedItemsPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTable invoiceDetailsTable;
    private ro.samlex.reelcash.ui.components.JContactPanel invoicedContactPanel;
    private javax.swing.JPanel invoicedItemsPanel;
    private javax.swing.JScrollPane invoicedItemsTableScroller;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JSpinner numberSpinner;
    // End of variables declaration//GEN-END:variables
}
