package com.google.code.reelcash.swing;

import com.google.code.reelcash.actions.ExitAction;
import com.google.code.reelcash.swing.invoices.JInvoicesPanel;
import com.google.code.reelcash.util.ScreenUtils;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author andrei.olar
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = -1730752996574728739L;
    private static MainFrame instance;

    /** Creates new form MainFrame */
    private MainFrame() {
        initComponents();
        add(new JInvoicesPanel());
    }

    /**
     * Gets the singleton instance of this frame.
     *
     * @return
     */
    public static MainFrame getInstance() {
        if (null == instance)
            instance = new MainFrame();
        return instance;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JMenuBar();
        appMenu = new javax.swing.JMenu();
        registryItem = new javax.swing.JMenuItem();
        regQuitSeparator = new javax.swing.JPopupMenu.Separator();
        quitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        usersGuideItem = new javax.swing.JMenuItem();
        aboutItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/google/code/reelcash/swing/resources"); // NOI18N
        setTitle(bundle.getString("MainFrame_title")); // NOI18N
        setName("mainFrame"); // NOI18N

        appMenu.setText("File");

        registryItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        registryItem.setMnemonic('r');
        registryItem.setText(Resources.getString("registryItem_text")); // NOI18N
        registryItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registryItemActionPerformed(evt);
            }
        });
        appMenu.add(registryItem);
        registryItem.getAccessibleContext().setAccessibleName("Edit registries");

        appMenu.add(regQuitSeparator);

        quitItem.setAction(new ExitAction(0));
        quitItem.setMnemonic('q');
        quitItem.setText(Resources.getString("quitItem_text")); // NOI18N
        quitItem.setToolTipText(Resources.getString("quitItem_tooltip")); // NOI18N
        appMenu.add(quitItem);

        mainMenu.add(appMenu);

        helpMenu.setText("Edit");

        usersGuideItem.setText("jMenuItem1");
        helpMenu.add(usersGuideItem);

        aboutItem.setText("jMenuItem1");
        helpMenu.add(aboutItem);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registryItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registryItemActionPerformed
        JFrame registryFrame = new JFrame("Registry");
        registryFrame.setLayout(new BorderLayout());
        registryFrame.add(JRegistriesPanel.getInstance(), BorderLayout.CENTER);
        ScreenUtils.computeMinimumSize(registryFrame);
        ScreenUtils.centerWindowOnScreen(registryFrame);
        registryFrame.setVisible(true);
    }//GEN-LAST:event_registryItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutItem;
    private javax.swing.JMenu appMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem quitItem;
    private javax.swing.JPopupMenu.Separator regQuitSeparator;
    private javax.swing.JMenuItem registryItem;
    private javax.swing.JMenuItem usersGuideItem;
    // End of variables declaration//GEN-END:variables
}
