package com.google.code.reelcash.swing;

import com.google.code.reelcash.actions.ExitAction;
import com.google.code.reelcash.swing.invoices.JInvoicesPanel;
import javax.swing.JDialog;

/**
 *
 * @author andrei.olar
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = -1730752996574728739L;
    private static MainFrame instance;

    /** Creates new form MainFrame */
    private MainFrame() {
        initComponents();
        add(new JInvoicesPanel());
    }

    /**
     * Gets the singleton instance of this frame.
     *
     * @return
     */
    public static MainFrame getInstance() {
        if (null == instance) {
            instance = new MainFrame();
        }
        return instance;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenu = new javax.swing.JMenuBar();
        appMenu = new javax.swing.JMenu();
        registriesItem = new javax.swing.JMenuItem();
        regToQuitSep = new javax.swing.JPopupMenu.Separator();
        quitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/google/code/reelcash/swing/resources"); // NOI18N
        setTitle(bundle.getString("MainFrame_title")); // NOI18N
        setName("mainFrame"); // NOI18N

        appMenu.setText(Resources.getString("MainFrame_appMenu_text")); // NOI18N

        registriesItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, java.awt.event.InputEvent.CTRL_MASK));
        registriesItem.setMnemonic('r');
        registriesItem.setText(Resources.getString("MainFrame_registriesItem_text")); // NOI18N
        registriesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onEditRegistriesRequested(evt);
            }
        });
        appMenu.add(registriesItem);
        appMenu.add(regToQuitSep);

        quitItem.setAction(new ExitAction(0));
        quitItem.setText(Resources.getString("MainFrame_quitItem_text")); // NOI18N
        appMenu.add(quitItem);

        mainMenu.add(appMenu);

        setJMenuBar(mainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onEditRegistriesRequested(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onEditRegistriesRequested
        JDialog dialog = new JDialog(this, Resources.getString("MainFrame_title"), true);
        dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        dialog.add(JRegistriesPanel.getInstance());
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_onEditRegistriesRequested
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu appMenu;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem quitItem;
    private javax.swing.JPopupMenu.Separator regToQuitSep;
    private javax.swing.JMenuItem registriesItem;
    // End of variables declaration//GEN-END:variables
}
