package com.google.code.reelcash.swing;

import com.google.code.reelcash.swing.invoices.JInvoicesPanel;

/**
 *
 * @author andrei.olar
 */
public class MainFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = -1730752996574728739L;
    private static MainFrame instance;

    /** Creates new form MainFrame */
    private MainFrame() {
        initComponents();
        add(new JInvoicesPanel());
    }

    /**
     * Gets the singleton instance of this frame.
     *
     * @return
     */
    public static MainFrame getInstance() {
        if (null == instance)
            instance = new MainFrame();
        return instance;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/google/code/reelcash/swing/resources"); // NOI18N
    setTitle(bundle.getString("MainFrame_title")); // NOI18N
    setName("mainFrame"); // NOI18N

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
