/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JContactPanel.java
 *
 * Created on Apr 27, 2010, 10:50:14 AM
 */

package com.google.code.reelcash.swing.invoices;

/**
 *
 * @author andrei.olar
 */
public class JContactPanel extends javax.swing.JPanel {

    /** Creates new form JContactPanel */
    public JContactPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    contentsPanel = new javax.swing.JPanel();
    nameLabel = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    surnameLabel = new javax.swing.JLabel();
    surnameField = new javax.swing.JTextField();
    addressLabel = new javax.swing.JLabel();
    addressField = new javax.swing.JTextField();
    postalCodeLabel = new javax.swing.JLabel();
    postalCodeField = new javax.swing.JFormattedTextField();
    countryLabel = new javax.swing.JLabel();
    countryCombo = new javax.swing.JComboBox();
    regionLabel = new javax.swing.JLabel();
    regionCombo = new javax.swing.JComboBox();
    countyLabel = new javax.swing.JLabel();
    countyCombo = new javax.swing.JComboBox();
    cityLabel = new javax.swing.JLabel();
    cityCombo = new javax.swing.JComboBox();
    editCountriesButton = new javax.swing.JButton();
    editRegionsButton = new javax.swing.JButton();
    editCountiesButton = new javax.swing.JButton();
    editCitiesButton = new javax.swing.JButton();
    commandPanel = new javax.swing.JPanel();
    acceptButton = new javax.swing.JButton();
    rejectButton = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    contentsPanel.setMinimumSize(new java.awt.Dimension(400, 50));
    contentsPanel.setPreferredSize(new java.awt.Dimension(400, 270));
    contentsPanel.setLayout(new java.awt.GridBagLayout());

    nameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    nameLabel.setLabelFor(nameField);
    nameLabel.setText("Name:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(nameLabel, gridBagConstraints);
    nameLabel.getAccessibleContext().setAccessibleName("");

    nameField.setMinimumSize(new java.awt.Dimension(75, 20));
    nameField.setPreferredSize(new java.awt.Dimension(125, 20));
    nameField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nameFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(nameField, gridBagConstraints);

    surnameLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    surnameLabel.setLabelFor(surnameField);
    surnameLabel.setText("Surname:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(surnameLabel, gridBagConstraints);

    surnameField.setMinimumSize(new java.awt.Dimension(75, 20));
    surnameField.setPreferredSize(new java.awt.Dimension(125, 20));
    surnameField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        surnameFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(surnameField, gridBagConstraints);

    addressLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    addressLabel.setLabelFor(addressField);
    addressLabel.setText("Address:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(addressLabel, gridBagConstraints);

    addressField.setMinimumSize(new java.awt.Dimension(75, 20));
    addressField.setPreferredSize(new java.awt.Dimension(200, 20));
    addressField.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        addressFieldActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(addressField, gridBagConstraints);

    postalCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    postalCodeLabel.setLabelFor(postalCodeField);
    postalCodeLabel.setText("Postal code:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(postalCodeLabel, gridBagConstraints);

    try {
      postalCodeField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("######")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(postalCodeField, gridBagConstraints);

    countryLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    countryLabel.setText("Country:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(countryLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.8;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
    contentsPanel.add(countryCombo, gridBagConstraints);

    regionLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    regionLabel.setText("Region:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(regionLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.8;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
    contentsPanel.add(regionCombo, gridBagConstraints);

    countyLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    countyLabel.setText("County:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(countyLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.8;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
    contentsPanel.add(countyCombo, gridBagConstraints);

    cityLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    cityLabel.setText("City:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 5, 5);
    contentsPanel.add(cityLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.8;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 0);
    contentsPanel.add(cityCombo, gridBagConstraints);

    editCountriesButton.setText("edit ...");
    editCountriesButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        editCountriesButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(editCountriesButton, gridBagConstraints);
    editCountriesButton.getAccessibleContext().setAccessibleName("");

    editRegionsButton.setText("edit ...");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(editRegionsButton, gridBagConstraints);

    editCountiesButton.setText("edit ...");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 6;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(editCountiesButton, gridBagConstraints);

    editCitiesButton.setText("edit ...");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 7;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 5, 15);
    contentsPanel.add(editCitiesButton, gridBagConstraints);

    add(contentsPanel, java.awt.BorderLayout.CENTER);

    commandPanel.setMinimumSize(new java.awt.Dimension(100, 70));
    commandPanel.setPreferredSize(new java.awt.Dimension(467, 70));
    commandPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 25, 20));

    acceptButton.setMnemonic('a');
    acceptButton.setText("Accept");
    acceptButton.setToolTipText("Accepts the current information about the contact");
    acceptButton.setActionCommand("accept");
    commandPanel.add(acceptButton);
    acceptButton.getAccessibleContext().setAccessibleName("accept");

    rejectButton.setMnemonic('r');
    rejectButton.setText("Reject");
    rejectButton.setToolTipText("Discards the contact information");
    rejectButton.setActionCommand("reject");
    commandPanel.add(rejectButton);
    rejectButton.getAccessibleContext().setAccessibleName("reject");

    add(commandPanel, java.awt.BorderLayout.PAGE_END);
  }// </editor-fold>//GEN-END:initComponents

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void surnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameFieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void editCountriesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCountriesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editCountriesButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton acceptButton;
  private javax.swing.JTextField addressField;
  private javax.swing.JLabel addressLabel;
  private javax.swing.JComboBox cityCombo;
  private javax.swing.JLabel cityLabel;
  private javax.swing.JPanel commandPanel;
  private javax.swing.JPanel contentsPanel;
  private javax.swing.JComboBox countryCombo;
  private javax.swing.JLabel countryLabel;
  private javax.swing.JComboBox countyCombo;
  private javax.swing.JLabel countyLabel;
  private javax.swing.JButton editCitiesButton;
  private javax.swing.JButton editCountiesButton;
  private javax.swing.JButton editCountriesButton;
  private javax.swing.JButton editRegionsButton;
  private javax.swing.JTextField nameField;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JFormattedTextField postalCodeField;
  private javax.swing.JLabel postalCodeLabel;
  private javax.swing.JComboBox regionCombo;
  private javax.swing.JLabel regionLabel;
  private javax.swing.JButton rejectButton;
  private javax.swing.JTextField surnameField;
  private javax.swing.JLabel surnameLabel;
  // End of variables declaration//GEN-END:variables

}
