/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDocumentPanel.java
 *
 * Created on Apr 27, 2010, 10:49:38 AM
 */
package com.google.code.reelcash.swing.invoices;

import com.google.code.reelcash.data.ReelcashDataSource;
import com.google.code.reelcash.data.sql.QueryMediator;
import com.google.code.reelcash.model.DataRowComboModel;
import com.google.code.reelcash.swing.ComboListCellRenderer;
import com.google.code.reelcash.util.MsgBox;
import java.sql.SQLException;

/**
 *
 * @author andrei.olar
 */
public class JDocumentPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = -6048890672950334891L;
    private static final String selectIssuers = "select b.id, b.name from businesses b inner join business_permissions bp on bp.business_id = b.id inner join permissions p on p.id = bp.permission_id where p.name='emit';";
    private static final String selectRecipients = "select b.id, b.name from businesses b inner join business_permissions bp on bp.business_id = b.id inner join permissions p on p.id = bp.permission_id where p.name='receive';";
    private QueryMediator mediator;
    private DataRowComboModel issuerModel;
    private DataRowComboModel recipientModel;
    private ComboListCellRenderer renderer;

    /** Creates new form JDocumentPanel */
    public JDocumentPanel() {
        initComponents();
        issuerCombo.setModel(getIssuerModel());
        recipientCombo.setModel(getRecipientModel());
        renderer = new ComboListCellRenderer(1);
        issuerCombo.setRenderer(renderer);
        recipientCombo.setRenderer(renderer);
    }

    private QueryMediator getMediator() {
        if (null == mediator)
            mediator = new QueryMediator(ReelcashDataSource.getInstance());
        return mediator;
    }

    private DataRowComboModel getIssuerModel() {
        if (null == issuerModel) {
            issuerModel = new DataRowComboModel();
            try {
                issuerModel.fill(getMediator().fetchSimple(selectIssuers));
                issuerModel.setValueMemberIndex(0);
                issuerModel.setDisplayMemberIndex(1);
            }
            catch (SQLException e) {
                MsgBox.exception(e);
            }
        }
        return issuerModel;
    }

    private DataRowComboModel getRecipientModel() {
        if (null == recipientModel) {
            recipientModel = new DataRowComboModel();
            try {
                recipientModel.fill(getMediator().fetchSimple(selectRecipients));
                recipientModel.setValueMemberIndex(0);
                recipientModel.setDisplayMemberIndex(1);
            }
            catch (SQLException e) {
                MsgBox.exception(e);
            }
        }
        return recipientModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    numberLabel = new javax.swing.JLabel();
    numberField = new javax.swing.JTextField();
    issuerLabel = new javax.swing.JLabel();
    issuerCombo = new javax.swing.JComboBox();
    recipientLabel = new javax.swing.JLabel();
    recipientCombo = new javax.swing.JComboBox();
    typeLabel = new javax.swing.JLabel();
    typeCombo = new javax.swing.JComboBox();
    dateIssuedLabel = new javax.swing.JLabel();
    dateIssuedField = new javax.swing.JFormattedTextField();
    dateDueLabel = new javax.swing.JLabel();
    dateDueField = new javax.swing.JFormattedTextField();

    setPreferredSize(new java.awt.Dimension(145, 204));
    setLayout(new java.awt.GridBagLayout());

    numberLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    numberLabel.setText("Document No.");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 5);
    add(numberLabel, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
    add(numberField, gridBagConstraints);

    issuerLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    issuerLabel.setText("Issuer");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 5);
    add(issuerLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
    add(issuerCombo, gridBagConstraints);

    recipientLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    recipientLabel.setText("Recipient");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 5);
    add(recipientLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
    add(recipientCombo, gridBagConstraints);

    typeLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    typeLabel.setText("Document type");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 5);
    add(typeLabel, gridBagConstraints);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
    add(typeCombo, gridBagConstraints);

    dateIssuedLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    dateIssuedLabel.setText("Issued on");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 5);
    add(dateIssuedLabel, gridBagConstraints);

    dateIssuedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
    add(dateIssuedField, gridBagConstraints);

    dateDueLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    dateDueLabel.setText("Due by");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.weightx = 0.2;
    gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 5);
    add(dateDueLabel, gridBagConstraints);

    dateDueField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 15);
    add(dateDueField, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JFormattedTextField dateDueField;
  private javax.swing.JLabel dateDueLabel;
  private javax.swing.JFormattedTextField dateIssuedField;
  private javax.swing.JLabel dateIssuedLabel;
  private javax.swing.JComboBox issuerCombo;
  private javax.swing.JLabel issuerLabel;
  private javax.swing.JTextField numberField;
  private javax.swing.JLabel numberLabel;
  private javax.swing.JComboBox recipientCombo;
  private javax.swing.JLabel recipientLabel;
  private javax.swing.JComboBox typeCombo;
  private javax.swing.JLabel typeLabel;
  // End of variables declaration//GEN-END:variables
}
