/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFiscalSeriesPanel.java
 *
 * Created on Apr 26, 2010, 5:19:21 PM
 */

package com.google.code.reelcash.swing.invoices;

import com.google.code.reelcash.data.documents.SeriesRangeNode;
import com.google.code.reelcash.data.layout.FlatLayoutNode;
import com.google.code.reelcash.model.DataRowTableModel;

/**
 *
 * @author andrei.olar
 */
public class JFiscalSeriesPanel extends javax.swing.JPanel {
    private static final long serialVersionUID = -7689325987410024914L;
    private static final String TABLE_NAME = "series_ranges";
    private DataRowTableModel tableModel;

    /** Creates new form JFiscalSeriesPanel */
    public JFiscalSeriesPanel() {
        initComponents();
    }

    private DataRowTableModel getTableModel() {
        if(null == tableModel) {
            tableModel = new DataRowTableModel(SeriesRangeNode.getInstance());
        }
        return tableModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    titleLabel = new javax.swing.JLabel();
    seriesScroller = new javax.swing.JScrollPane();
    seriesTable = new javax.swing.JTable();

    setLayout(new java.awt.BorderLayout());

    titleLabel.setText("Please choose the fiscal series range to use ... ");
    add(titleLabel, java.awt.BorderLayout.NORTH);

    seriesTable.setModel(getTableModel());
    seriesScroller.setViewportView(seriesTable);

    add(seriesScroller, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane seriesScroller;
  private javax.swing.JTable seriesTable;
  private javax.swing.JLabel titleLabel;
  // End of variables declaration//GEN-END:variables

}
