/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInvoiceDetailsPanel.java
 *
 * Created on May 2, 2010, 1:25:40 PM
 */

package com.google.code.reelcash.swing.invoices;

/**
 *
 * @author cusi
 */
public class JInvoiceDetailsPanel extends javax.swing.JPanel {

    /** Creates new form JInvoiceDetailsPanel */
    public JInvoiceDetailsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        masterInfo = new javax.swing.JPanel();
        numberLabel = new javax.swing.JLabel();
        numberText = new javax.swing.JLabel();
        detailsPanel = new javax.swing.JPanel();
        detailsDisplayPanel = new javax.swing.JPanel();
        detailOperationsBar = new javax.swing.JToolBar();
        createDetailButton = new javax.swing.JButton();
        editDetailButton = new javax.swing.JButton();
        deleteDetailButton = new javax.swing.JButton();
        detailsTableScroller = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        detailDataPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        masterInfo.setMinimumSize(new java.awt.Dimension(0, 150));
        masterInfo.setPreferredSize(new java.awt.Dimension(400, 200));
        masterInfo.setLayout(new java.awt.GridBagLayout());

        numberLabel.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(92, 177, 93, 178);
        masterInfo.add(numberLabel, gridBagConstraints);

        numberText.setText("jLabel1");
        masterInfo.add(numberText, new java.awt.GridBagConstraints());

        add(masterInfo, java.awt.BorderLayout.PAGE_START);

        detailsPanel.setLayout(new java.awt.CardLayout());

        detailsDisplayPanel.setLayout(new java.awt.BorderLayout());

        detailOperationsBar.setRollover(true);

        createDetailButton.setText("jButton1");
        createDetailButton.setFocusable(false);
        createDetailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createDetailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        detailOperationsBar.add(createDetailButton);

        editDetailButton.setText("jButton1");
        editDetailButton.setFocusable(false);
        editDetailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editDetailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        detailOperationsBar.add(editDetailButton);

        deleteDetailButton.setText("jButton1");
        deleteDetailButton.setFocusable(false);
        deleteDetailButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteDetailButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        deleteDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDetailButtonActionPerformed(evt);
            }
        });
        detailOperationsBar.add(deleteDetailButton);

        detailsDisplayPanel.add(detailOperationsBar, java.awt.BorderLayout.PAGE_START);

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        detailsTableScroller.setViewportView(detailsTable);

        detailsDisplayPanel.add(detailsTableScroller, java.awt.BorderLayout.CENTER);

        detailsPanel.add(detailsDisplayPanel, "disp");

        detailDataPanel.setLayout(new java.awt.GridBagLayout());
        detailsPanel.add(detailDataPanel, "data");

        add(detailsPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDetailButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteDetailButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDetailButton;
    private javax.swing.JButton deleteDetailButton;
    private javax.swing.JPanel detailDataPanel;
    private javax.swing.JToolBar detailOperationsBar;
    private javax.swing.JPanel detailsDisplayPanel;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JTable detailsTable;
    private javax.swing.JScrollPane detailsTableScroller;
    private javax.swing.JButton editDetailButton;
    private javax.swing.JPanel masterInfo;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel numberText;
    // End of variables declaration//GEN-END:variables

}
