/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInvoicesPanel.java
 *
 * Created on Jun 21, 2010, 3:10:02 PM
 */

package com.google.code.reelcash.swing.invoices;

/**
 *
 * @author andrei.olar
 */
public class JInvoicesPanel extends javax.swing.JPanel {

    /** Creates new form JInvoicesPanel */
    public JInvoicesPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    operationBar = new javax.swing.JToolBar();
    addButton = new javax.swing.JButton();
    delButton = new javax.swing.JButton();
    tableScroller = new javax.swing.JScrollPane();
    invoicesTable = new javax.swing.JTable();

    setLayout(new java.awt.BorderLayout());

    operationBar.setFloatable(false);
    operationBar.setOrientation(1);
    operationBar.setDoubleBuffered(true);

    addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/google/code/reelcash/images/toolbar/add_small.png"))); // NOI18N
    addButton.setFocusable(false);
    addButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    addButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    operationBar.add(addButton);

    delButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/google/code/reelcash/images/toolbar/delete_small.png"))); // NOI18N
    delButton.setFocusable(false);
    delButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    delButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    operationBar.add(delButton);

    add(operationBar, java.awt.BorderLayout.WEST);

    invoicesTable.setModel(null);
    tableScroller.setViewportView(invoicesTable);

    add(tableScroller, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton addButton;
  private javax.swing.JButton delButton;
  private javax.swing.JTable invoicesTable;
  private javax.swing.JToolBar operationBar;
  private javax.swing.JScrollPane tableScroller;
  // End of variables declaration//GEN-END:variables

}
