/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JInvoiceWizard.java
 *
 * Created on Apr 27, 2010, 4:39:36 PM
 */
package com.google.code.reelcash.swing.invoices;

import com.google.code.reelcash.data.DataRow;
import com.google.code.reelcash.data.ReelcashDataSource;
import com.google.code.reelcash.data.sql.QueryMediator;
import com.google.code.reelcash.swing.ComboListCellRenderer;
import com.google.code.reelcash.util.MsgBox;
import java.awt.CardLayout;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;

/**
 *
 * @author andrei.olar
 */
public class JInvoiceWizard extends javax.swing.JFrame {

    private static final long serialVersionUID = 4789786767938489010L;
    private ListModel seriesListModel;
    private final String[] pages = new String[]{"welcome", "document", "series"};
    private int currentPageIndex = 0;

    /** Creates new form JInvoiceWizard */
    public JInvoiceWizard() {
        initComponents();
        seriesList.addAncestorListener(new InvoiceWizardAncestorListener());
        setControlState();
    }

    private void setControlState() {
        prevPageButton.setEnabled(currentPageIndex > 0);
        final String nameKey = currentPageIndex < pages.length - 1 ? "next_page_button_text" : "finish_button_text";
        final String mnemonicKey = currentPageIndex < pages.length - 1 ? "next_page_button_mnemonic" : "finish_button_mnemonic";
        nextPageButton.setText(InvoiceResources.getString(nameKey));
        nextPageButton.setMnemonic(InvoiceResources.getString(mnemonicKey).charAt(0));
    }

    private void nextPage() {
        if (currentPageIndex >= pages.length - 1) {
            MsgBox.info(InvoiceResources.getString("no_more_pages"));
            return;
        }
        currentPageIndex++;
        ((CardLayout) wizardPages.getLayout()).show(wizardPages, pages[currentPageIndex]);
        setControlState();
    }

    private void prevPage() {
        if (1 > currentPageIndex) {
            MsgBox.info(InvoiceResources.getString("no_more_pages"));
            return;
        }
        currentPageIndex--;
        ((CardLayout) wizardPages.getLayout()).show(wizardPages, pages[currentPageIndex]);
        setControlState();
    }

    public ListModel getSeriesListModel() {
        if (null == seriesListModel)
            seriesListModel = new DefaultListModel();
        return seriesListModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    wizardPages = new javax.swing.JPanel();
    welcomePage = new javax.swing.JScrollPane();
    welcomeTextPane = new javax.swing.JTextPane();
    createDocumentPage = new com.google.code.reelcash.swing.invoices.JDocumentPanel();
    seriesRangePanel = new javax.swing.JPanel();
    seriesScrollPane = new javax.swing.JScrollPane();
    seriesList = new javax.swing.JList();
    controlPanel = new javax.swing.JPanel();
    prevPageButton = new javax.swing.JButton();
    nextPageButton = new javax.swing.JButton();
    closeButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    wizardPages.setLayout(new java.awt.CardLayout());

    welcomePage.setPreferredSize(new java.awt.Dimension(500, 30));

    welcomeTextPane.setText("<html><body><h1>Welcome</h1><p>This wizard will allow you to create an invoice. After the invoice is created, you will be able to add details to it (i.e. the goods you're invoicing)</p></body></html>");
    welcomePage.setViewportView(welcomeTextPane);

    wizardPages.add(welcomePage, "welcome");

    createDocumentPage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, InvoiceResources.getString("create_document_title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
    wizardPages.add(createDocumentPage, "document");

    seriesRangePanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, InvoiceResources.getString("select_series_range_title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)), javax.swing.BorderFactory.createEmptyBorder(15, 15, 30, 15))); // NOI18N
    seriesRangePanel.setLayout(new java.awt.BorderLayout());

    seriesList.setModel(getSeriesListModel());
    seriesScrollPane.setViewportView(seriesList);

    seriesRangePanel.add(seriesScrollPane, java.awt.BorderLayout.CENTER);

    wizardPages.add(seriesRangePanel, "series");

    getContentPane().add(wizardPages, java.awt.BorderLayout.CENTER);

    controlPanel.setBackground(java.awt.SystemColor.controlHighlight);
    controlPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 15));

    prevPageButton.setMnemonic('p');
    prevPageButton.setText("Previous");
    prevPageButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        prevPageButtonActionPerformed(evt);
      }
    });
    controlPanel.add(prevPageButton);

    nextPageButton.setMnemonic('n');
    nextPageButton.setText("Next");
    nextPageButton.setPreferredSize(new java.awt.Dimension(73, 23));
    nextPageButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nextPageButtonActionPerformed(evt);
      }
    });
    controlPanel.add(nextPageButton);

    closeButton.setMnemonic('c');
    closeButton.setText("Close");
    closeButton.setPreferredSize(new java.awt.Dimension(73, 23));
    closeButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        closeButtonActionPerformed(evt);
      }
    });
    controlPanel.add(closeButton);

    getContentPane().add(controlPanel, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void prevPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevPageButtonActionPerformed
        prevPage();
    }//GEN-LAST:event_prevPageButtonActionPerformed

    private void nextPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageButtonActionPerformed

        if (currentPageIndex < pages.length - 1)
            nextPage();
    }//GEN-LAST:event_nextPageButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JInvoiceWizard().setVisible(true);
            }
        });
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton closeButton;
  private javax.swing.JPanel controlPanel;
  private com.google.code.reelcash.swing.invoices.JDocumentPanel createDocumentPage;
  private javax.swing.JButton nextPageButton;
  private javax.swing.JButton prevPageButton;
  private javax.swing.JList seriesList;
  private javax.swing.JPanel seriesRangePanel;
  private javax.swing.JScrollPane seriesScrollPane;
  private javax.swing.JScrollPane welcomePage;
  private javax.swing.JTextPane welcomeTextPane;
  private javax.swing.JPanel wizardPages;
  // End of variables declaration//GEN-END:variables

    private class InvoiceWizardAncestorListener implements AncestorListener {

        private final ComboListCellRenderer renderer = new ComboListCellRenderer(1);

        public void ancestorAdded(AncestorEvent event) {
            if (JInvoiceWizard.this.seriesList.equals(event.getSource())) {
                QueryMediator mediator = new QueryMediator(ReelcashDataSource.getInstance());
                try {
                    DataRow[] rows = mediator.fetchSimple("select id, prefix || counter || suffix || ' - ' || ((max_value-counter)/inc_step) || 'p' as desc from series_ranges where counter<max_value;");
                    for (DataRow row : rows)
                        ((DefaultListModel) getSeriesListModel()).addElement(row);
                    JInvoiceWizard.this.seriesList.setCellRenderer(renderer);
                }
                catch (SQLException e) {
                    MsgBox.error(e.getLocalizedMessage());
                }
            }
        }

        public void ancestorRemoved(AncestorEvent event) {
            ((DefaultListModel) getSeriesListModel()).removeAllElements();
        }

        public void ancestorMoved(AncestorEvent event) {
            // nothing to be done here
        }
    }
}
